// Code generated by qtc from "pkgconfig.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line magefiles/pkgconfig.qtpl:1
package main

//line magefiles/pkgconfig.qtpl:2
import (
	"go/build"
	"os"
	"path/filepath"
)

//line magefiles/pkgconfig.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line magefiles/pkgconfig.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line magefiles/pkgconfig.qtpl:8
func StreamGenPkgConfig(qw422016 *qt422016.Writer, cefBinaryDir string) {
//line magefiles/pkgconfig.qtpl:10
	gopath := os.Getenv("GOPATH")
	if gopath == "" {
		gopath = build.Default.GOPATH
	}
	goPathBin := filepath.ToSlash(gopath) + "/bin"

//line magefiles/pkgconfig.qtpl:15
	qw422016.N().S(`# Generated by $THIS
target=`)
//line magefiles/pkgconfig.qtpl:17
	qw422016.E().S(goPathBin)
//line magefiles/pkgconfig.qtpl:17
	qw422016.N().S(`
libdir=${target}
includedir=`)
//line magefiles/pkgconfig.qtpl:19
	qw422016.E().S(cefBinaryDir)
//line magefiles/pkgconfig.qtpl:19
	qw422016.N().S(`

Name: cefingo
Version: 0.1
Description: cefingo 
Cflags: -I${includedir}
Libs: -L${libdir} -lcef
`)
//line magefiles/pkgconfig.qtpl:26
}

//line magefiles/pkgconfig.qtpl:26
func WriteGenPkgConfig(qq422016 qtio422016.Writer, cefBinaryDir string) {
//line magefiles/pkgconfig.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line magefiles/pkgconfig.qtpl:26
	StreamGenPkgConfig(qw422016, cefBinaryDir)
//line magefiles/pkgconfig.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line magefiles/pkgconfig.qtpl:26
}

//line magefiles/pkgconfig.qtpl:26
func GenPkgConfig(cefBinaryDir string) string {
//line magefiles/pkgconfig.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line magefiles/pkgconfig.qtpl:26
	WriteGenPkgConfig(qb422016, cefBinaryDir)
//line magefiles/pkgconfig.qtpl:26
	qs422016 := string(qb422016.B)
//line magefiles/pkgconfig.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line magefiles/pkgconfig.qtpl:26
	return qs422016
//line magefiles/pkgconfig.qtpl:26
}

// # -Wno-discarded-qualifiers
// # -Wno-incompatible-pointer-types
